language: python
python: 2.7
sudo: false
branches:
  only:
  - release
  - master
  - /^\d\.\d+$/
env:
- TOXENV=py27
install:
- pip install -U tox twine wheel codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sphy
  password:
    secure: f3IaU6q+k8EJYlh0ep+SXlUMB3yqmHTiCIiRYNIegyXG9tQLif7iCl0oPkZ1a212Wrt+CYx225ZSPgsTjS4/ZBTlyMsVZsKKidhty68AaYglWAkFmEex4bV4L7wNrktaWppnZmy5Nv4D2+6VCvB9KjN00WZ+oeJRIk3KFczvozgqdZVHxgZ2nrWneUZ03SnwraUYuagSGwV8i1I9YY9v6Vgf8tKPBlu90/2Exro/4DwS80H8Q3JwDyxlDtE8tu9AH7waH+kPAetBm7ut+6plQGmC9VZ3NXdNHwz/gseNwLSPAKXUBhlp2lgH9aRJpunYA6ABLQ+hCOhrTD/BXdk+Zd5yKGC+b32BVYsvPY/FAwe23KX4ZH8FArsB1TTxoVSIsQ5H/MdR8CSuyK+yWto9sgEjSRyg0fUVtI1urRcbqejOaVeu4E4H3CSICrTarJUpxPA3BWGagK8F0K5amGWzuHNQyvGWSDqN6DMjeuYIpzI4etkWfqF4Ezqx2nt5DhLQh7nYeC0Dcp1v7M/S/TA6H5BntSIgQl1fzeMGKhzRcr9wKPptxvvMenw9uyTVf0StIBcBzSuzgDoYXLyO2yyaHTi2rCn2Fu1Sgl49pjD0P+Ip6kGwegbnSHDrFA8ognbQc/zFSGNRdMNm6p0ScdLfw3rPhIkOkwXRuo22lp5MkEg=
  on:
    tags: false
    repo: philoprove/currying
    branch: release
